[package]
name = "mixini"
version = "0.1.0"
authors = ["Allen <fairingrey@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.19"
dotenv = "0.15.0"
lettre = "0.10.0-beta.4"
libreauth = "0.14.1"
oso = "0.12.2"
oso-derive = "0.12.2"
redis = { version = "0.20.0", features = ["aio", "tokio-comp", "tokio-native-tls-comp"], default-features = false }
serde = { version = "1.0.125", features = ["derive"] }
serde_json = "1.0.64"
sqlx = { version = "0.5.2", features = ["runtime-tokio-native-tls", "postgres", "uuid", "chrono", "json"] }
surf = "2.2.0"
tantivy = "0.14.0"
tide = "0.16.0"
tokio = { version = "1.5.0", features = ["rt-multi-thread", "macros", "sync"] }
