[package]
name = "server"
version = "0.1.0"
authors = ["Allen <fairingrey@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-std = { version = "1.9.0", features = ["attributes"] }
chrono = "0.4.19"
dotenv = "0.15.0"
lettre = "0.10.0-beta.4"
libreauth = "0.14.1"
oso = "0.12.2"
oso-derive = "0.12.2"
redis = "0.20.0"
serde = { version = "1.0.125", features = ["derive"] }
serde_json = "1.0.64"
sqlx = { version = "0.5.2", features = ["runtime-async-std-native-tls", "postgres", "uuid"] }
surf = "2.2.0"
tantivy = "0.14.0"
tide = "0.16.0"
